allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - esbuild@0.28.1
  - brace-expansion@1.1.16 || 1.1.17 || 1.1.18 || 2.1.2 || 2.1.3 || 2.1.4 || 5.0.8 || 5.0.9
  - immutable@4.3.9
  - fast-uri@3.1.3 || 3.1.4 || 3.1.5 || 3.1.6
  - undici@6.28.0 || 7.29.0
  - "@xmldom/xmldom@0.8.14 || 0.8.15"
overrides:
  "@hono/node-server@<2.0.5": ^2.0.5
  brace-expansion@<1.1.18: ^1.1.18
  brace-expansion@>=2.0.0 <2.1.4: ^2.1.4
  brace-expansion@>=4.0.0 <5.0.9: ^5.0.9
  dompurify@<=3.4.11: ^3.4.12
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  fast-uri@>=3.0.0 <3.1.5: ^3.1.5
  hono@<4.12.34: ^4.12.34
  immutable@<4.3.9: ^4.3.9
  ip-address@<=10.3.0: ^10.3.1
  js-yaml@>=4.0.0 <4.3.1: ^4.3.1
  lodash-es@<=4.17.23: ^4.17.24
  mermaid@>=11.0.0-alpha.1 <11.16.1: ^11.16.1
  nanoid@<3.3.8: ^3.3.8
  nanoid@>=4.0.0 <5.0.9: ^5.0.9
  postcss@<=8.5.22: ^8.5.23
  tar@<=7.5.20: ^7.5.21
  undici@<6.28.0: ^6.28.0
  undici@>=7.0.0 <7.29.0: ^7.29.0
  vite: "catalog:"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vite-plus: 0.3.1
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
